services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MINIO_ENDPOINT: http://minio-service:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: 123456MinIO
      MINIO_BUCKET: videos
      RUST_LOG: info
      GRPC_PORT: 50051
    ports:
      - "50051:50051"
      - "4000-5000:4000-5000/udp"
    volumes:
      - ../..:/workspaces:cached
    networks:
      - devcontainer-net
    command: sleep infinity

  minio-service:
    image: minio/minio:latest
    container_name: minio-service
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 123456MinIO
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - devcontainer-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  minio-data:

networks:
  devcontainer-net:
    driver: bridge
